#!/usr/bin/env bash

set -Eeuo pipefail
exitcode=0

    printf "18.3: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm 'localhost:5000/ghcr.io/gui/postgres-with-extensions:build-cache-18.3' 2>&1 || true)
    if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
      exitcode=1
      echo "Error"
      echo "$output"
      echo
    elif [[ "$output" =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      exitcode=1
      echo "Unexpected Error"
      echo "$output"
      echo
    fi

    printf "18.3-bookworm: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm 'localhost:5000/ghcr.io/gui/postgres-with-extensions:build-cache-18.3-bookworm' 2>&1 || true)
    if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
      exitcode=1
      echo "Error"
      echo "$output"
      echo
    elif [[ "$output" =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      exitcode=1
      echo "Unexpected Error"
      echo "$output"
      echo
    fi

    printf "17.9: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm 'localhost:5000/ghcr.io/gui/postgres-with-extensions:build-cache-17.9' 2>&1 || true)
    if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
      exitcode=1
      echo "Error"
      echo "$output"
      echo
    elif [[ "$output" =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      exitcode=1
      echo "Unexpected Error"
      echo "$output"
      echo
    fi

    printf "17.9-bookworm: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm 'localhost:5000/ghcr.io/gui/postgres-with-extensions:build-cache-17.9-bookworm' 2>&1 || true)
    if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
      exitcode=1
      echo "Error"
      echo "$output"
      echo
    elif [[ "$output" =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      exitcode=1
      echo "Unexpected Error"
      echo "$output"
      echo
    fi

    printf "16.13: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm 'localhost:5000/ghcr.io/gui/postgres-with-extensions:build-cache-16.13' 2>&1 || true)
    if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
      exitcode=1
      echo "Error"
      echo "$output"
      echo
    elif [[ "$output" =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      exitcode=1
      echo "Unexpected Error"
      echo "$output"
      echo
    fi

    printf "16.13-bookworm: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm 'localhost:5000/ghcr.io/gui/postgres-with-extensions:build-cache-16.13-bookworm' 2>&1 || true)
    if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
      exitcode=1
      echo "Error"
      echo "$output"
      echo
    elif [[ "$output" =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      exitcode=1
      echo "Unexpected Error"
      echo "$output"
      echo
    fi

    printf "15.17: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm 'localhost:5000/ghcr.io/gui/postgres-with-extensions:build-cache-15.17' 2>&1 || true)
    if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
      exitcode=1
      echo "Error"
      echo "$output"
      echo
    elif [[ "$output" =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      exitcode=1
      echo "Unexpected Error"
      echo "$output"
      echo
    fi

    printf "15.17-bookworm: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm 'localhost:5000/ghcr.io/gui/postgres-with-extensions:build-cache-15.17-bookworm' 2>&1 || true)
    if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
      exitcode=1
      echo "Error"
      echo "$output"
      echo
    elif [[ "$output" =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      exitcode=1
      echo "Unexpected Error"
      echo "$output"
      echo
    fi

    printf "14.22: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm 'localhost:5000/ghcr.io/gui/postgres-with-extensions:build-cache-14.22' 2>&1 || true)
    if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
      exitcode=1
      echo "Error"
      echo "$output"
      echo
    elif [[ "$output" =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      exitcode=1
      echo "Unexpected Error"
      echo "$output"
      echo
    fi

    printf "14.22-bookworm: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm 'localhost:5000/ghcr.io/gui/postgres-with-extensions:build-cache-14.22-bookworm' 2>&1 || true)
    if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
      exitcode=1
      echo "Error"
      echo "$output"
      echo
    elif [[ "$output" =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      exitcode=1
      echo "Unexpected Error"
      echo "$output"
      echo
    fi


exit "$exitcode"
